config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'directories#view'
  resources :directories, only: %i(index show create update destroy) do
    get :view
  end
  resource :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/directory.rb
class Directory < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :children, class_name: self, foreign_key: :parent_id, dependent: :destroy
  belongs_to :parent, class_name: self, optional: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :directory
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController

  # root page
  def view
    root = Directory.find_by_parent_id(nil)
    @directories = Directory.where(parent_id: [nil, root.id]).group_by(&:parent_id)
  end

  # Get recursively
  def index
    @directories = Directory.includes(:items)
    @directories = @directories.group_by(&:parent_id)
  end

  # only json
  def show
    dir_id = params[:id]
    @directory = if dir_id == 'root'
                   Directory.where(parent_id: nil).take
                 else
                   Directory.find(dir_id)
                 end
    render json: {
      id: @directory.id,
      directories: @directory.children,
      items: @directory.items,
    }
  end

  def create
    parent = Directory.find(params[:parent_id])
    directory = Directory.new(name: 'new dir', parent: parent)

    if directory.save
      redirect_to directories_path
    else
      redirect_to directories_path
    end
  end

  def update
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    directory = Directory.find(params[:directory_id])
    item = Item.new(subject: 'new item', directory: directory)

    if item.save
      render json: ['ok']
    else
      render json: ['error']
    end
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directories/_rec_render_dir.haml
.dir.open{class: dir.parent.nil? && 'root'}
  .dir_name= dir.name
  %span.nav-toggle
    %span= link_to 'Add Directory', directories_path({parent_id: dir.id}), method: :post
    %span= link_to 'Add Item', items_path(directory_id: dir.id), method: :post, remote: true
    %span= link_to 'Delete Directory', directory_path(dir), method: :delete, remote: true

  - dirs = @directories[dir.id]
  - if defined?(recursible) && recursible.present? && dirs.present?
    - dirs.each do |child|
      = render partial: 'rec_render_dir', locals: {dir: child, recursible: true}
  - elsif dirs.present?
    - dirs.each do |child|
      .dir.close
        .dir_name= child.name
        %nav
        %span.nav-toggle
          %span= link_to 'Add Directory', directories_path({parent_id: child.id}), method: :post
          %span= link_to 'Add Item', items_path(directory_id: child.id), method: :post, remote: true
          %span= link_to 'Delete Directory', directory_path(child), method: :delete, remote: true

  %ul.files
    - dir.items.each do |item|
      %li= item.subject

app/views/directories/index.haml
%section.main
  - dir = @directories[nil]&.first
  - if dir
    = render partial: 'rec_render_dir', locals: {dir: dir, recursible: true}

app/views/directories/view.haml
- content_for(:javascript) do
  = javascript_include_tag 'webpack/directory'

%asside#dir-nav

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %title WebDir
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

    -if content_for?(:javascript)
      = yield(:javascript)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebDir</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>